// Code generated by "stringer -type=Operation -trimprefix=Op"; DO NOT EDIT.

package filters

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpInvalid-0]
	_ = x[OpNop-1]
	_ = x[OpNot-2]
	_ = x[OpAnd-3]
	_ = x[OpOr-4]
	_ = x[OpVarIsConst-5]
	_ = x[OpVarIsPure-6]
}

const _Operation_name = "InvalidNopNotAndOrVarIsConstVarIsPure"

var _Operation_index = [...]uint8{0, 7, 10, 13, 16, 18, 28, 37}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
